services:
  web:
    container_name: "web"
    working_dir: /app/django_app/
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../django_app/:/app/django_app/
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - pg_data


  pg_data:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data/


  smpp_client:
    working_dir: /app/django_app/
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: python manage.py start_smpp_client
    volumes:
      - ../django_app/:/app/django_app/
    depends_on:
      - pg_data
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONUNBUFFERED=1

  phone_register:
    working_dir: /app/django_app/
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../django_app/:/app/django_app/
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py parser"

volumes:
  pg_data: