# Generated by Django 5.1.3 on 2024-11-19 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_service', '0001_initial'),
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_send', models.DateTimeField(auto_now_add=True)),
                ('datetime_got', models.DateTimeField(blank=True, default=None, null=True)),
                ('sender', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sender.order')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register_service.number')),
            ],
        ),
    ]
